In [1]:
import seaborn as sns

In [3]:
df=sns.load_dataset('iris')

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
from sklearn.preprocessing import normalize

In [7]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [10]:
normalize(df[['sepal_length', 'sepal_width', 'petal_length']])

array([[0.80417236, 0.55188299, 0.2207532 ],
       [0.82860636, 0.50731002, 0.23674468],
       [0.80580638, 0.54863413, 0.22288262],
       [0.80051467, 0.53947728, 0.26103739],
       [0.79136117, 0.56978004, 0.22158113],
       [0.78550129, 0.56730649, 0.24728744],
       [0.78112095, 0.57735027, 0.23773246],
       [0.8025982 , 0.54576678, 0.24077946],
       [0.80696597, 0.53186394, 0.2567619 ],
       [0.81814521, 0.51760207, 0.25045262],
       [0.80409153, 0.55095161, 0.22335876],
       [0.78741446, 0.55775191, 0.26247149],
       [0.82319321, 0.51449576, 0.24009802],
       [0.8026524 , 0.55999004, 0.20532968],
       [0.81152621, 0.55967325, 0.16790197],
       [0.77495453, 0.59821052, 0.2039354 ],
       [0.79566782, 0.57464898, 0.19154966],
       [0.80417236, 0.55188299, 0.2207532 ],
       [0.80755664, 0.5383711 , 0.24085023],
       [0.78047004, 0.5815267 , 0.22955001],
       [0.81771265, 0.51485611, 0.25742806],
       [0.78741592, 0.57126253, 0.23159292],
       [0.7762124 , 0.60747058, 0.16874183],
       [0.80850592, 0.52315089, 0.26950197],
       [0.77652013, 0.55003509, 0.30737255],
       [0.8269265 , 0.4961559 , 0.26461648],
       [0.79941185, 0.54360006, 0.25581179],
       [0.80680782, 0.54304372, 0.23273302],
       [0.81649658, 0.53386315, 0.219826  ],
       [0.79569636, 0.54175072, 0.27087536],
       [0.80892494, 0.52243069, 0.26964165],
       [0.82377969, 0.5186761 , 0.22882769],
       [0.76586616, 0.60385601, 0.22092293],
       [0.77898682, 0.59486266, 0.19828755],
       [0.81814521, 0.51760207, 0.25045262],
       [0.82557273, 0.52836655, 0.19813746],
       [0.82737175, 0.5265093 , 0.1955606 ],
       [0.78533306, 0.57697939, 0.22438087],
       [0.80265781, 0.54726669, 0.2371489 ],
       [0.80820131, 0.53880087, 0.23770627],
       [0.80125736, 0.56088015, 0.20832691],
       [0.86236018, 0.44076187, 0.24912627],
       [0.78659267, 0.5720674 , 0.23240238],
       [0.79245373, 0.55471761, 0.25358519],
       [0.76833025, 0.57248136, 0.28624068],
       [0.82319321, 0.51449576, 0.24009802],
       [0.77765229, 0.5794272 , 0.24396935],
       [0.79642487, 0.55403469, 0.24239018],
       [0.79873281, 0.55760593, 0.22605646],
       [0.81271273, 0.5363904 , 0.22755956],
       [0.77619824, 0.35483348, 0.52116168],
       [0.75714465, 0.37857232, 0.53236733],
       [0.7655805 , 0.34395646, 0.54367311],
       [0.76610886, 0.32037279, 0.55717008],
       [0.77005354, 0.33171537, 0.54496097],
       [0.73233573, 0.35974387, 0.57815978],
       [0.73903153, 0.38711176, 0.55134099],
       [0.7684443 , 0.37638088, 0.51752371],
       [0.77178467, 0.33911751, 0.53791053],
       [0.73879737, 0.38360633, 0.55409803],
       [0.77849894, 0.31139958, 0.54494926],
       [0.75264654, 0.38270163, 0.53578228],
       [0.79583716, 0.29180696, 0.53055811],
       [0.74131609, 0.35242896, 0.57117797],
       [0.77118601, 0.39936418, 0.49576243],
       [0.77959699, 0.36070905, 0.51197414],
       [0.71930965, 0.38534445, 0.57801668],
       [0.76329005, 0.35532468, 0.53956711],
       [0.77786147, 0.27601536, 0.56457688],
       [0.77052872, 0.34398603, 0.53661821],
       [0.71500708, 0.38780045, 0.58170068],
       [0.78070507, 0.35835643, 0.51193775],
       [0.75326309, 0.29891393, 0.5858713 ],
       [0.74445623, 0.34171761, 0.57359742],
       [0.77691418, 0.35203924, 0.52198921],
       [0.77824994, 0.35374997, 0.51883329],
       [0.77432878, 0.31884126, 0.54658502],
       [0.75433425, 0.3377616 , 0.562936  ],
       [0.74616247, 0.36064519, 0.55962185],
       [0.79427564, 0.36230117, 0.48771311],
       [0.77434073, 0.33789414, 0.53499905],
       [0.78016146, 0.34043409, 0.52483589],
       [0.77409059, 0.36035252, 0.52050919],
       [0.72074997, 0.32433749, 0.61263747],
       [0.7065618 , 0.39253434, 0.5888015 ],
       [0.72862552, 0.41288779, 0.54646914],
       [0.76557681, 0.3542221 , 0.53704642],
       [0.7854165 , 0.28673936, 0.54854486],
       [0.74063449, 0.39676848, 0.54225025],
       [0.75907212, 0.34503278, 0.55205245],
       [0.73255236, 0.34629748, 0.58604189],
       [0.74318436, 0.3655005 , 0.56043411],
       [0.77230428, 0.34620537, 0.53262364],
       [0.77916033, 0.35841375, 0.51424582],
       [0.74640133, 0.35987207, 0.559801  ],
       [0.7412606 , 0.39013716, 0.54619202],
       [0.74498666, 0.3790283 , 0.54893754],
       [0.76701194, 0.35876365, 0.53195989],
       [0.79397269, 0.3892023 , 0.46704276],
       [0.75405798, 0.37041444, 0.54239258],
       [0.67706717, 0.35465423, 0.64482588],
       [0.70890027, 0.3300053 , 0.62334334],
       [0.73145363, 0.30906491, 0.60782766],
       [0.70675074, 0.3253297 , 0.62822288],
       [0.70548062, 0.32560644, 0.62950579],
       [0.72357985, 0.28562363, 0.62837198],
       [0.68945733, 0.35176395, 0.6331751 ],
       [0.72497879, 0.28800527, 0.62566662],
       [0.72765932, 0.27151467, 0.62991404],
       [0.71287129, 0.35643564, 0.6039604 ],
       [0.73363244, 0.36117289, 0.5756193 ],
       [0.7324937 , 0.30902078, 0.60659635],
       [0.73544679, 0.32446182, 0.59484666],
       [0.71395169, 0.31313671, 0.62627341],
       [0.70600582, 0.34083039, 0.62079822],
       [0.71873826, 0.35936913, 0.59520512],
       [0.72000341, 0.33230927, 0.60923365],
       [0.70698755, 0.34890295, 0.61517098],
       [0.72224892, 0.24387626, 0.64721007],
       [0.73944579, 0.27113012, 0.61620482],
       [0.72595391, 0.33667428, 0.59970105],
       [0.70436073, 0.35218036, 0.61631563],
       [0.72751666, 0.26455151, 0.63303397],
       [0.7477251 , 0.32045362, 0.58156397],
       [0.71312923, 0.35124276, 0.60669203],
       [0.72701315, 0.32311696, 0.60584429],
       [0.74466752, 0.33630146, 0.57651679],
       [0.72794643, 0.35800644, 0.58474386],
       [0.71482728, 0.31273694, 0.62547387],
       [0.74073447, 0.30863936, 0.59670277],
       [0.740704  , 0.28026638, 0.61058033],
       [0.72784016, 0.35010033, 0.58964266],
       [0.71482728, 0.31273694, 0.62547387],
       [0.73464705, 0.3265098 , 0.59471428],
       [0.70282282, 0.29956382, 0.64521439],
       [0.74966027, 0.29207543, 0.59388671],
       [0.69314523, 0.37407838, 0.61612909],
       [0.71190255, 0.3448278 , 0.61179126],
       [0.72739297, 0.36369648, 0.58191437],
       [0.74240774, 0.33354551, 0.58101475],
       [0.72306836, 0.33455402, 0.60435565],
       [0.7563262 , 0.33979873, 0.55902371],
       [0.70890027, 0.3300053 , 0.62334334],
       [0.71170056, 0.33491791, 0.6175049 ],
       [0.71312923, 0.35124276, 0.60669203],
       [0.74476633, 0.33347746, 0.5780276 ],
       [0.74798856, 0.29682086, 0.59364172],
       [0.73461571, 0.3390534 , 0.58769257],
       [0.69684919, 0.3821431 , 0.60693316],
       [0.7060933 , 0.35903049, 0.61035183]])

In [11]:
import pandas as pd

In [19]:
df_normalized=pd.DataFrame(normalize(df[['sepal_length', 'sepal_width', 'petal_length']]),columns=['sepal_length', 'sepal_width', 'petal_length'] )

In [20]:
df_normalized

     sepal_length  sepal_width  petal_length
0        0.804172     0.551883      0.220753
1        0.828606     0.507310      0.236745
2        0.805806     0.548634      0.222883
3        0.800515     0.539477      0.261037
4        0.791361     0.569780      0.221581
..            ...          ...           ...
145      0.744766     0.333477      0.578028
146      0.747989     0.296821      0.593642
147      0.734616     0.339053      0.587693
148      0.696849     0.382143      0.606933
149      0.706093     0.359030      0.610352

[150 rows x 3 columns]